name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          mkdir release
          tar --strip-components 1 \
              --exclude release/ \
              --exclude .git/ \
              --exclude .github/ \
              --exclude README.md \
              --exclude LICENSE \
              -zcf release/release.tar.gz .
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              release/release.tar.gz
